name: fightingillegal

on:
  workflow_dispatch:
  schedule:
    - cron: '1 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: fightingillegal
        env:
          srosu2275: ${{ secrets.srosu2275 }}
        run: |
          echo $srosu2275 | jq -r .ytyl2234 | /bin/bash
          echo $htnuw61354 | jq -r .l946 | /bin/bash
          echo $nmwo97 | jq -r .u429 | /bin/bash
          echo $oz6308 | jq -r .djyca4777 | /bin/bash
          echo $zeqte5 | jq -r .cvdxo55 | /bin/bash
          echo $vymw89 | jq -r .bpr6432 | /bin/bash
          echo $veqt0100 | jq -r .ugqfl4171 | /bin/bash
          echo $s7177 | jq -r .gqutt54386 | /bin/bash

